# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46255f7ce32eb241ff8d403dd7efc04e0303a09fc05b043b6d8295e2d2e4bf7175df4b9d4d2c76236dc46c39ce7a920e9a9c767644594ffb4073a4d6d4b13d8a

test:
  secret_key_base: 2022c4f8646f2c6b085b624a5081e57d77ee6fd761788c91f5c310b7aa463448931431df1c9d5ab780a3a2a5ffd5a4ed30479e6e2990811ffe6c5dbbb2da971c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
